name: squeak
description: Pet Application
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.25+25

environment:
  sdk: '>=3.1.0 <4.0.0'


dependencies:
  animated_bottom_navigation_bar: ^1.3.3
  app_links: ^6.3.2
  carousel_slider: ^5.0.0
  chewie: ^1.8.5
  #
  cloud_firestore: ^5.4.4
  comment_tree: ^0.3.0
  dio: ^5.7.0
 # drop_down_search_field: ^1.0.6
  cached_network_image: ^3.3.1
  firebase_messaging: ^15.1.3
  flutter:
    sdk: flutter


  flutter_bloc: ^8.1.6
  flutter_image_compress: ^2.3.0
  flutter_inappwebview: ^6.1.5
  flutter_local_notifications: ^17.2.4
  flutter_localizations:
    sdk: flutter






  flutter_offline: ^4.0.0
  flutter_test:
    sdk: flutter
  flutter_to_pdf: ^0.2.2
  geocoding: ^3.0.0
 # geolocator: ^13.0.2
  google_fonts: ^6.2.1
  http: ^1.2.2
  iconly: ^1.0.1
  image_picker: ^1.1.2
  lottie: ^3.1.3
  package_info_plus: ^8.2.1
  permission_handler: ^11.3.1

  phone_text_field: ^0.0.7
  printing: ^5.13.3
  qr_flutter: ^4.1.0
  quickalert: ^1.1.0
  share_plus: ^10.1.1
  shared_preferences: ^2.3.2
  shimmer: ^3.0.0
  sqflite: ^2.4.1
  table_calendar: ^3.1.2
  toastification: ^2.3.0
  url_launcher: ^6.3.0
  video_player: ^2.9.2
  widget_circular_animator: ^1.0.0
  #workmanager: ^0.5.3
  animate_do: ^3.3.4  # Use the latest version compatible with Flutter 3.27.1
  audioplayers: ^5.2.1
 
 # drop_down_search_field: ^1.1.3
  #cached_network_image: ^3.4.1


flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/
    - shorebird.yaml
    - assets/notification.mp3

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true
